name: Debug with SSH

on:
  workflow_dispatch:  # trigger manually from GitHub UI

jobs:
  ssh-debug:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Start SSH via tmate
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true   # only repo owner can connect
